name: Mypy Check

on: [pull_request]
jobs:
  mypy:
    name: runner / mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tsuyoshicho/action-mypy@v3
        with:
          github_token: ${{ secrets.github_token }}
          target: pronotepy
          mypy_flags: "--disallow-untyped-defs --disallow-incomplete-defs"
          reporter: github-pr-check
